version: "3.5"

services:
    php-fpm-vo-doctrine:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            XDEBUG_CONFIG: remote_host=192.168.1.45
        depends_on:
            - mysql-vo-doctrine
        volumes:
            - ../:/application
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infrastructure-overrides.ini
    webserver-vo-doctrine:
        image: nginx:alpine
        ports:
            - "8082:80"
        depends_on:
            - php-fpm-vo-doctrine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../:/application
    mysql-vo-doctrine:
        build:
            context: .
            dockerfile: mysql/Dockerfile
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=vo_doctrine
